## 50 câu hỏi ngắn về Numpy

### Câu hỏi 1: import numpy dưới bí danh np và xem phiên bản

In [2]:
import numpy as np
print(np.__version__)

2.2.3


### Câu hỏi 2: Làm thế nào để tạo mảng 1 chiều?

In [3]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### Câu hỏi 3: Làm thế nào để tạo một mảng boolean?

In [9]:
import numpy as np

In [10]:
a = np.array([1, 0, 1, 0, 0, 1, 0])

In [11]:
b = np.where(a == 1, True, False) #or b = np.array(a, dtype=bool)


In [12]:
print(b)

[ True False  True False False  True False]


### Câu hỏi 4: Làm thế nào để trích xuất các mục thỏa mãn một điều kiện nhất định từ mảng 1 chiều?
Ví dụ: Trích xuất tất cả các số lẻ từ mảng

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])
b = np.where(a % 2 != 0)
print(a[b])
#or
odd = a[a%2!=0]
print(odd)


[1 3 5 7]
[1 3 5 7]


### Câu hỏi 5: Làm thế nào để thay thế các mục thỏa mãn một điều kiện bằng một giá trị khác trong mảng numpy?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])
#np.where(condition, x, y) -> trả về value
#np.where(condition) -> trả về index
b = np.where(a % 2 != 0, -1, a)
print(b)
print(a)

[-1  2 -1  4 -1  6 -1  8 10]
[ 2  4  6  8 10]


### Câu hỏi 6: Làm thế nào để thay thế các mục thỏa mãn một điều kiện mà không ảnh hưởng đến mảng ban đầu?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1 mà không thay đổi arr

In [27]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])
b = a.copy()
b[np.where(b % 2 != 0)] = -1
print(b)

[-1  2 -1  4 -1  6 -1  8 10]


### Câu hỏi 7: Làm thế nào để định hình lại một mảng?

In [5]:
#Su dung reshape
#Lấy mảng b từ câu trên
b = b.reshape(3, 3)
print(b)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 10]]


### Câu hỏi 8: Làm thế nào để xếp chồng hai mảng theo chiều dọc?

In [33]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])
b = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19])
c = np.vstack((a, b))
print(c)

[[ 1  2  3  4  5  6  7  8 10]
 [11 12 13 14 15 16 17 18 19]]


### Câu hỏi 9: Làm thế nào để xếp chồng hai mảng theo chiều ngang?

In [34]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])
b = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19])
c = np.concatenate((a, b), axis=0)
print(c)

[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19]


### Câu hỏi 10: Làm thế nào để tạo các chuỗi tùy chỉnh trong numpy mà không cần mã hóa cứng?
Ví dụ: 
Input: a = np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [35]:
#Mã hóa cứng tứng là tạo sẵn 1 mãng lun
a = np.array([1, 2, 3])

a_repeat = np.repeat(a, 3)
a_tile = np.tile(a, 3)
result = np.concatenate((a_repeat, a_tile))
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Câu hỏi 11. Làm thế nào để lấy các mục chung giữa hai mảng numpy python?
Ví dụ: 
Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

        b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: array([2, 4])

In [37]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [38]:
common = np.intersect1d(a, b)
print("Cac so giong nhau la: ", common)

Cac so giong nhau la:  [2 4]


### Câu hỏi 12. Làm thế nào để xóa khỏi một mảng những mục tồn tại trong mảng khác? 
Ví dụ: Input: a = np.array([1,2,3,4,5])

              b = np.array([5,6,7,8,9])

Output: array([1,2,3,4])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

common = np.intersect1d(a, b)
#nhung ptu a ko co trong common
a = a[a!=common]
print(a)

[1 2 3 4]


### Câu hỏi 13. Làm thế nào để lấy các vị trí mà các phần tử của hai mảng khớp nhau?

Ví dụ: 

Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

       b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: (array([1, 3, 5, 7]),)

In [6]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
print(c[0])

[1 3 5 7]


### Câu hỏi 14. Làm thế nào để trích xuất tất cả các số trong một phạm vi nhất định từ một mảng numpy?

Ví dụ: 
Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

Output: (array([6, 9, 10]),)

In [12]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = []
l, r = 5, 10
for i in a:
    if i >= l and i <= r:
        result.append(int(i))
print(result)

[6, 9, 10]


### Câu hỏi 16. Làm thế nào để hoán đổi hai cột trong một mảng numpy 2 chiều? 

In [32]:
a = np.array([[1, 2, 3],
            [4, 5, 6],])

print(a[::, ::-1])   # đảo cột

[[3 2 1]
 [6 5 4]]


### Câu hỏi 17. Làm thế nào để hoán đổi hai hàng trong một mảng numpy 2 chiều? 

In [30]:
a = np.array([[1, 2, 3],
            [4, 5, 6],])

a = a[::-1,::]
print(a)

[[4 5 6]
 [1 2 3]]


### Câu hỏi 18. Làm thế nào để đảo ngược các hàng của một mảng 2 chiều? 

In [ ]:
#Dao nguoc cac hang tuc la dao cac cot
a = np.array([[1, 2, 3],
            [4, 5, 6],])

print(a[::, ::-1])

[[3 2 1]
 [6 5 4]]


### Câu hỏi 19. Làm thế nào để đảo ngược các cột của một mảng 2 chiều?

In [ ]:
#Dao nguoc cac cot tuc la dao cac hang
a = np.array([[1, 2, 3],
            [4, 5, 6],])

a = a[::-1,::]
print(a)

[[4 5 6]
 [1 2 3]]


### Câu hỏi 20. Làm thế nào để tạo một mảng 2 chiều chứa các số thực ngẫu nhiên giữa 5 và 10?

In [5]:
import numpy as np
n, m = 3, 3
rng = np.random.default_rng()
a = rng.uniform(5, 10, (3, 3))
print(a)

[[5.82533375 7.84689681 6.88942005]
 [9.11444985 5.11812979 9.33736749]
 [9.97280348 5.89798793 8.43181089]]


### Câu hỏi 21. Làm thế nào để chỉ in 3 chữ số thập phân trong mảng numpy python? 

In [ ]:
import numpy as np
n, m = 3, 3
rng = np.random.default_rng()
a = rng.uniform(low=5.0, high=10.0, size=(n, m))
a_round = np.round(a, 3)
print(a_round)     


[[6.527 8.678 5.543]
 [7.699 6.595 6.175]
 [9.994 7.226 6.057]]
[[6.527 8.678 5.543]
 [7.699 6.595 6.175]
 [9.994 7.226 6.057]]


### Câu hỏi 22. Làm thế nào để in đẹp một mảng numpy bằng cách loại bỏ ký hiệu khoa học (như 1e10)? 

In [ ]:
import numpy as np
n, m = 3, 3
rng = np.random.default_rng()
a = rng.uniform(low=5.0, high=10000000000.0, size=(100, 100))
#su dung suppress_small
print(np.array2string(a, formatter={'float_kind':lambda x:f"{x:.5f}"}))                                 

[[371044757.64295 2565813472.52379 2357742875.44858]
 [9818837114.73374 1432409774.45291 5194215609.36613]
 [4334878810.05229 1738061984.77366 5016175118.62843]]


### Câu hỏi 24. Làm thế nào để in toàn bộ mảng numpy mà không cần cắt bớt

In [6]:
#Su dung print options cua numpy
import numpy as np
rng = np.random.default_rng()
a = rng.uniform(low=5.0, high=10000.0, size=(10, 10))
with np.printoptions(threshold=np.inf, linewidth=200):
    print(a)

[[7781.21177376 4782.24022197 4464.56361237 3040.51121736 7112.91216135 9227.56788299 9431.26181287 7267.38911679 5721.69147084 5827.15834324]
 [7594.70482609 1729.72406671 3968.25428194 4064.6531743   729.21731639 8497.79244628 7843.17770504 4391.24508884 9727.96835074 6087.3749055 ]
 [7420.21483592  823.42766716 9876.37166782 1466.52205292 4263.43023182 3581.16217163 2804.71198833 9350.11516795 4869.26936201 1932.39912697]
 [4505.07003242  996.52552213 9339.70239901 3064.461355   1019.83040343 9930.35740833 9653.18203858 3211.06637146 7006.82307717 6041.26075232]
 [7855.70576563 7050.75046644  184.1094103  1827.35620974 9313.19957151 6152.09015086 3182.65293067 3256.95445573 2033.01581139 9581.9009351 ]
 [7065.13135987 5665.70708972 6985.61280144 9985.22942649 3486.81859479 2625.35190912 4780.39366978 6251.18571777 1567.59077848 6243.41641625]
 [7213.52214652 7373.83668344 6900.05330855  822.13024477 9192.44682122 3538.4746429  9058.58768084 3072.56466359 4790.191464   9017.80464894]

### Câu hỏi 28. Làm thế nào để tính giá trị trung bình, trung vị, độ lệch chuẩn của một mảng numpy?

In [9]:
#tb: .mean(), median: .median(), do lech chuan: .std()
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8 ,9, 10])
print(np.mean(a))
print(np.median(a))
print(np.std(a))

5.5
5.5
2.8722813232690143


### Câu hỏi 29. Làm thế nào để chuẩn hóa một mảng sao cho các giá trị nằm chính xác trong khoảng từ 0 đến 1?

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8 ,9, 10])
amin, amax = np.min(a), np.max(a)
range = amax - amin if amin != amax else 1.0

scaled = (a-amin) / range
print(scaled)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### Câu hỏi 30. Làm thế nào để tính điểm softmax?

In [ ]:
# Tại sao cần softmax?
# Output mô hình thường là giá trị bất kỳ (có thể âm, không giới hạn).
# Softmax “chuẩn hóa” chúng thành dạng giống xác suất, dễ diễn giải và so sánh.
# Nhờ đó ta chọn lớp dự đoán bằng cách lấy lớp có điểm softmax cao nhất.
# Thường sài trong mạng neuron để đưa ra predict
a = np.array([1.0, 2.0, 0.1, 4.24])
exp_a = np.exp(a - np.max(a))
softmax = exp_a / np.sum(exp_a)
print(softmax)

[0.03371706 0.09165248 0.01370834 0.86092212]


### Câu hỏi 32. Làm thế nào để chèn các giá trị ở các vị trí ngẫu nhiên trong một mảng?

Ví dụ: Chèn giá trị 0 vào 20 vị trí ngẫu nhiên trong tập dữ liệu a

In [26]:
import random
a = [1, 2, 3, 5, 6, 7, 9]
print(a)
a.insert(random.randint(0, 7), 4)
print(a)

[1, 2, 3, 5, 6, 7, 9]
[1, 4, 2, 3, 5, 6, 7, 9]


### Câu hỏi 34. Làm thế nào để lọc một mảng numpy dựa trên hai hoặc nhiều điều kiện?

Ví dụ: Lọc các hàng của a có các giá trị của (cột thứ 3) > 1,5 và các giá trị (cột thứ 1) < 5,0

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = (a[:, 2] > 1.5) & (a[:,1] < 5.0)
b = a[mask]
print(b)


[[1 2 3]]


### Câu hỏi 36. Làm thế nào để tìm mối tương quan giữa hai cột của mảng numpy?

In [37]:
# np.corrcoef
#col2 = col1 + 2 ==> Tương quan hoàn hảo
a = np.array([
    [1, 3, 1],
    [7, 9, 1],
    [7, 9, 9]
])

col1 = a[:, 0]   # cột 1    
col2 = a[:, 1]   # cột 2
corr1 = np.corrcoef(col1, col2)
corr = np.corrcoef(col1, col2)[0, 1]
print("Ma trận hệ số tương quan:\n", corr1)
print("Hệ số tương quan giữa cột 1 và cột 2:", corr)

Ma trận hệ số tương quan:
 [[1. 1.]
 [1. 1.]]
Hệ số tương quan giữa cột 1 và cột 2: 1.0


### Câu hỏi 44. Làm thế nào để sắp xếp một mảng 2D theo một cột

In [44]:
a = np.array([
    [1, 3, 1],
    [7, 5, 1],
    [4, 6, 9]
])
a = a.reshape(9, 1)
a.sort(axis=0)
print(a)

[[1]
 [1]
 [1]
 [3]
 [4]
 [5]
 [6]
 [7]
 [9]]


### Câu hỏi 45. Làm thế nào để tìm giá trị thường xuyên nhất trong một mảng numpy?

In [ ]:
a = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3])
values = np.unique(a, return_counts=False)
print(values)
#----
counts = np.unique(a, return_counts=True)[1]
print(counts)
#count
index = np.argmax(counts)
mode = values[index]
print(mode)

[1 2 3]
[3 3 4]
3


### Câu hỏi 47. Làm thế nào để thay thế tất cả các giá trị lớn hơn một giá trị nhất định thành một ngưỡng nhất định?

Ví dụ: Từ mảng a, thay thế tất cả các giá trị lớn hơn 30 đến 30 và nhỏ hơn 10 đến 10.

In [49]:
import numpy as np
a = np.array([5, 12, 25, 35, 8, 50, 7, 15])

a[a>20] = 20

a[a<15] = 15

print(a)

[15 15 20 20 15 20 15 15]


### Câu hỏi 48. Làm thế nào để lấy vị trí của n giá trị hàng đầu từ một mảng numpy?

Ví dụ: Lấy vị trí của 5 giá trị lớn nhất trong một mảng cho trước a.

In [46]:
import numpy as np
a = ([5, 12, 25, 35, 8, 50, 7, 15])
a.sort(reverse=True)

print(a[:5])

[50, 35, 25, 15, 12]


### Câu hỏi 50. Làm thế nào để chuyển đổi một mảng các mảng thành một mảng phẳng 1 chiều?

In [48]:
import numpy as np

a = np.array([[1, 3, 3],
              [4, 4, 6],
              [7, 1, 9]])

flat = a.flatten()
print(flat)


[1 3 3 4 4 6 7 1 9]
